[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "VideoViewer"
version = "0.1.0"
description = "A video view tool."
authors = [{ name = "yeehua", email = "yeehua@live.cn" }]
dependencies = ["numpy>=1.21", "requests"]
